/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/track': typeof ApiTrackRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/track': typeof ApiTrackRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/track': typeof ApiTrackRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/api/track' | '/api/admin/login' | '/api/admin/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/api/track' | '/api/admin/login' | '/api/admin/stats'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/track'
    | '/api/admin/login'
    | '/api/admin/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiTrackRoute: typeof ApiTrackRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiTrackRoute: ApiTrackRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
